GET http://localhost:3000/reserva
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJtYWtvQGdtYWlsLmNvbSIsInJvbCI6IkNsaWVudGUiLCJpYXQiOjE3MjczMzcxNzQsImV4cCI6MTcyNzM0MDc3NCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.xrgjr_-ZcDiiLd4lX4xNoxIwJIXA1Q1ul3i01zH7UhE

GET http://localhost:3000/reserva/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJtYXJjb3ZhbGRlczU3NkBnbWFpbC5jb20iLCJyb2wiOiJBZG1pbiIsImlhdCI6MTcyNzMzNTA4NywiZXhwIjoxNzI3MzM4Njg3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0._25wjrc1L5R3-NbLlOg-LvFzGTpg8lF1IjGhia10dUU