DELETE http://localhost:3000/reserva/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJtYWtvQGdtYWlsLmNvbSIsInJvbCI6IkNsaWVudGUiLCJpYXQiOjE3MjczODIwNzgsImV4cCI6MTcyNzM4NTY3OCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.Lbh038gtUEwW7YPFX6xvMKqRoJSoma0RTVKxCJAF5Ng